workflows:
  flutter-build:
    name: Flutter Build
    instance_type: mac_mini
    environment:
      flutter: stable
    scripts:
      - name: Create Flutter project if missing
        script: |
          if [ ! -f "pubspec.yaml" ]; then
            flutter create .
          fi
      - name: Install dependencies
        script: flutter pub get
      - name: Build iOS
        script: flutter build ios --no-codesign

