name: flutter_midi_controller
description: Un projet Flutter simple

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

environment:
  sdk: '^3.7.0'
